packages/app/src/components/inspector/ColorInputFieldWithPicker.tsx
packages/app/src/components/swatches/ColorSwatch.tsx

I think this could be move to another file but you can validate me first if the implementation it's good to go 😄

design and action completed (#8)

---

packages/app/src/containers/LayerStyleInspector.tsx
packages/app/src/containers/LayerThemeInspector.tsx
packages/app/src/containers/SwatchesToolbar.tsx
packages/app/src/containers/ThemeWindow.tsx
packages/noya-designsystem/src/components/Button.tsx
packages/noya-state/src/reducers/application.ts

Add  a new theme ![image](https://user-images.githubusercontent.com/16924758/113789141-32a0e280-9704-11eb-98e5-9adeb8f0d96a.png)
Disabled if not selected
New actions! 
We should change the the in the prompt! But it works!

Layertheme inspector

---

packages/app/src/containers/SwatchesToolbar.tsx
packages/noya-state/src/reducers/application.ts

this is faster than trying to fix the merge errors

Delete Button Layer - I created a new branch from main

---

packages/noya-state/src/reducers/application.ts
packages/noya-state/src/selectors.ts

Update layer with changes in theme style

---

packages/app/src/containers/PageList.tsx
packages/noya-state/src/models/index.ts
packages/noya-state/src/models/page.json
packages/noya-state/src/reducers/application.ts

Solve #23. There could be a cleaner way of updating the ids, but I think this feature it's working great!

improve-pages

---

packages/app/src/components/theme/LayerStylesGrid.tsx
packages/app/src/components/theme/SwatchesGrid.tsx
packages/app/src/containers/ThemeWindow.tsx
packages/noya-designsystem/src/components/GridView.tsx

delete from context menu

---

.husky/pre-commit
packages/app/src/components/inspector/NameInspector.tsx
packages/app/src/components/theme/LayerStylesGrid.tsx
packages/app/src/components/theme/SwatchesGrid.tsx
packages/app/src/containers/SwatchesGroups.tsx
packages/app/src/containers/SwatchesInspector.tsx
packages/app/src/containers/ThemeGroups.tsx
packages/app/src/containers/ThemeWindow.tsx
packages/app/src/containers/Workspace.tsx
packages/app/src/utils/createSwatchTree.ts
packages/noya-designsystem/src/components/GridView.tsx
packages/noya-designsystem/src/utils/withSeparatorElements.ts
packages/noya-state/src/reducers/application.ts
packages/noya-utils/src/__tests__/delimitedPath.test.ts
packages/noya-utils/src/__tests__/sortBy.test.ts
packages/noya-utils/src/delimitedPath.ts
packages/noya-utils/src/index.ts
packages/noya-utils/src/sortBy.ts

Handles groups and ungroups but stills need improvements when it comes to nested groups.

group and ungroup actions, change name

---

packages/noya-state/src/reducers/application.ts

This branch needs to be merged with the the group theme branch so it handles swatches and theme styles grouping too

Add to current group 

---

packages/noya-utils/src/__tests__/sortBy.test.ts

Tests for either key, when the values are the same or there is an empty space. Is there another case?
(Solves #31)

More test for sortby

---

packages/noya-state/src/reducers/application.ts
packages/noya-state/src/selectors.ts

Solves #33.
I am leaving it as a draft as I mentioned in the issue because I don't think the implementation it's optimal.

Theme Color updates all layers/styles

---

packages/app/src/containers/Inspector.tsx
packages/app/src/containers/ThemeTextInspector.tsx
packages/noya-state/src/reducers/textStyleReducer.ts
packages/noya-state/src/reducers/themeReducer.ts

Similar to the theme layer inspector.
There is a weird preview bug were the preview and the cahgnes aren't syncing correctly.

Theme Text Style Inspector

---

packages/app/src/containers/LayerList.tsx
packages/noya-state/src/models/index.ts
packages/noya-state/src/models/symbolInstance.json
packages/noya-state/src/models/symbolMaster.json
packages/noya-state/src/reducers/applicationReducer.ts
packages/noya-state/src/reducers/layerReducer.ts
packages/noya-state/src/reducers/pageReducer.ts
packages/noya-state/src/selectors/indexPathSelectors.ts
packages/noya-state/src/selectors/layerSelectors.ts
packages/noya-state/src/selectors/pageSelectors.ts

Allows to create symbols from the LayerList. It's creates a masterSymbol in a Symbols page and if the page doesn't exist it creates it.

Create Symbols from Inspector

---

packages/app/src/components/theme/ColorSwatch.tsx
packages/app/src/components/theme/SymbolsGrid.tsx
packages/app/src/containers/LayerList.tsx
packages/app/src/containers/ThemeGroups.tsx
packages/app/src/containers/ThemeInspector.tsx
packages/app/src/containers/ThemeSymbolsInspector.tsx
packages/app/src/containers/ThemeToolbar.tsx
packages/app/src/containers/ThemeWindow.tsx
packages/noya-state/src/layers.ts
packages/noya-state/src/reducers/applicationReducer.ts
packages/noya-state/src/reducers/layerReducer.ts
packages/noya-state/src/reducers/themeReducer.ts
packages/noya-state/src/selectors/layerSelectors.ts
packages/noya-state/src/selectors/pageSelectors.ts
packages/noya-state/src/selectors/themeSelectors.ts

Show grid of symbols and allow to change name but no preview

Symbol in Theme tabs

---

packages/noya-state/src/reducers/canvasReducer.ts

Add drawn layers into artboards

---

packages/app/src/containers/Menubar.tsx
packages/app/src/contexts/ApplicationStateContext.tsx
packages/noya-renderer/package.json
packages/noya-state/src/models/document.ts
packages/noya-state/src/models/index.ts
packages/noya-state/src/models/meta.ts
packages/noya-state/src/models/sketchFile.ts
packages/noya-state/src/reducers/applicationReducer.ts
packages/noya-state/src/reducers/workspaceReducer.ts
yarn.lock

Support creating new files

---

packages/app/src/containers/Canvas.tsx
packages/app/src/utils/mouseEvent.ts
packages/noya-state/src/reducers/applicationReducer.ts
packages/noya-state/src/reducers/layerReducer.ts

I only added two commands for now, since we should share most commands with the layer list.

Add canvas context menu. Select all layers action

---

packages/app/src/components/inspector/SymbolInstanceOverridesRow.tsx
packages/app/src/components/inspector/SymbolMasterOverrideRow.tsx
packages/app/src/containers/AlignmentInspector.tsx
packages/app/src/containers/LayerList.tsx
packages/noya-designsystem/src/components/ListView.tsx
packages/noya-designsystem/src/components/TreeView.tsx

Improve TreeView layout

---

packages/app/src/containers/FillInspector.tsx
packages/app/src/containers/Inspector.tsx
packages/app/src/containers/SymbolInstanceInspector.tsx
packages/app/src/containers/ThemeStyleInspector.tsx
packages/app/src/containers/ThemeTextStyleInspector.tsx
packages/noya-state/src/reducers/symbolsReducer.ts

Basically reuses the fillInspector to work with tints and I also added some correction where selectin 'No Symbol' in the Override wasn't working

Symbols tint

---

packages/noya-react-canvaskit/src/components/Group.tsx
packages/noya-react-canvaskit/src/reconciler.tsx
packages/noya-react-canvaskit/src/types.ts
packages/noya-renderer/src/components/layers/SketchSymbolInstance.tsx

This implements symbol tinting

Draw tinted symbol instances

---

packages/app/src/components/inspector/ColorInputFieldWithPicker.tsx
packages/noya-designsystem/src/components/Button.tsx
packages/noya-state/src/reducers/themeReducer.ts

I am still figuring out the best way to change the SwatchId of the fill.

Swatches from Color Inspector

---

packages/app/src/components/icons/PointModeIcon.tsx
packages/app/src/components/inspector/CoordinatesInspector.tsx
packages/app/src/components/inspector/DimensionInput.tsx
packages/app/src/containers/Inspector.tsx
packages/app/src/containers/PointControlsInspector.tsx
packages/app/src/containers/PointCoordinatesInspector.tsx
packages/app/src/containers/Toolbar.tsx
packages/noya-designsystem/src/theme/light.ts
packages/noya-react-canvaskit/src/hooks/useStroke.ts
packages/noya-react-canvaskit/src/index.ts
packages/noya-renderer/src/components/EditablePath.tsx
packages/noya-renderer/src/components/HoverOutline.tsx
packages/noya-renderer/src/components/SketchFileRenderer.tsx
packages/noya-renderer/src/components/layers/SketchGroup.tsx
packages/noya-renderer/src/components/layers/SketchShape.tsx
packages/noya-renderer/src/hooks/useLayerFrameRect.ts
packages/noya-renderer/src/hooks/useLayerPath.ts
packages/noya-renderer/src/primitives.ts
packages/noya-renderer/src/primitives/path.ts
packages/noya-state/src/layers.ts
packages/noya-state/src/reducers/applicationReducer.ts
packages/noya-state/src/reducers/canvasReducer.ts
packages/noya-state/src/reducers/interactionReducer.ts
packages/noya-state/src/reducers/layerPropertyReducer.ts
packages/noya-state/src/reducers/pointReducer.ts
packages/noya-state/src/selectors/geometrySelectors.ts
packages/noya-state/src/selectors/pointSelectors.ts
packages/noya-state/src/selectors/selectors.ts

This adds path editing mode, which includes:
- A toolbar icon for entering this mode
- New inspectors for editing point type, radius, and coordinates
- A new way to render paths on the canvas
FYI @leannepepper

Path editing mode

---

packages/noya-renderer/src/components/EditablePath.tsx

Rendering control points 
closes #107

adding control points

---

packages/app/src/containers/Canvas.tsx
packages/app/src/containers/LayerList.tsx
packages/app/src/hooks/useLayerMenu.tsx
packages/noya-designsystem/src/components/internal/Menu.tsx
packages/noya-designsystem/src/index.tsx
packages/noya-designsystem/src/utils/createSectionedMenu.ts
packages/noya-state/src/layers.ts
packages/noya-state/src/reducers/applicationReducer.ts
packages/noya-state/src/reducers/layerPropertyReducer.ts
packages/noya-state/src/reducers/layerReducer.ts
packages/noya-state/src/selectors/geometrySelectors.ts

This PR simplifies complex context menu creation, and unifies the context menus for the LayerList and Canvas:

Improve layer context menu

---

packages/app/src/containers/Canvas.tsx
packages/noya-renderer/src/components/EditablePath.tsx
packages/noya-renderer/src/components/SketchFileRenderer.tsx
packages/noya-state/src/reducers/applicationReducer.ts
packages/noya-state/src/reducers/pointReducer.ts

Clicking control point clears selectedPointLists and selecting a point clears selectedContolPoint.
closes #109

Click to select control point

---

packages/app/src/components/inspector/BorderRow.tsx
packages/app/src/components/inspector/ColorInputFieldWithPicker.tsx
packages/app/src/components/inspector/ColorPickerAssetGrid.tsx
packages/app/src/components/inspector/ColorPickerGradient.tsx
packages/app/src/components/inspector/ColorPickerGradients.tsx
packages/app/src/components/inspector/ColorPickerSwatches.tsx
packages/app/src/components/inspector/FillRow.tsx
packages/app/src/components/inspector/GradientInspector.tsx
packages/app/src/containers/BorderInspector.tsx
packages/app/src/containers/FillInspector.tsx
packages/noya-designsystem/src/index.tsx
packages/noya-state/src/reducers/applicationReducer.ts
packages/noya-state/src/reducers/gradientReducer.ts
packages/noya-state/src/reducers/styleReducer.ts
packages/noya-state/src/reducers/themeReducer.ts
packages/noya-state/src/selectors/themeSelectors.ts

Allows to change a gradient from a list of gradient and add a new one from the inspector.
_I am still figuring out if there it's a way of attaching the gradient to the current selected gradient and how to delete an existing asset🤔_

Theme Gradient inspector

---

packages/app/src/containers/Canvas.tsx
packages/app/src/containers/ControlPointCoordinatesInspector.tsx
packages/app/src/containers/Inspector.tsx
packages/app/src/containers/PointControlsInspector.tsx
packages/noya-state/src/reducers/applicationReducer.ts
packages/noya-state/src/reducers/pointReducer.ts
packages/noya-state/src/selectors/pointSelectors.ts

Adding ability to change control points in pathEdit mode. 
closes #110

Control point inspector

---

packages/app/src/containers/PageList.tsx
packages/app/src/containers/Workspace.tsx
packages/noya-designsystem/package.json
packages/noya-designsystem/src/components/GridView.tsx
packages/noya-designsystem/src/components/ListView.tsx
packages/noya-designsystem/src/components/ScrollArea.tsx
packages/noya-designsystem/src/index.tsx
packages/noya-designsystem/src/theme/dark.ts
packages/noya-designsystem/src/theme/light.ts
yarn.lock

This adds a custom scroll area, to prevent the width from changing when a scroll bar is present/hidden.

Custom ScrollArea

---

packages/app/src/components/inspector/ColorInspector.tsx
packages/app/src/components/inspector/DimensionInput.tsx
packages/app/src/components/inspector/DimensionsInspector.tsx
packages/app/src/components/inspector/FillInputFieldWithPicker.tsx
packages/app/src/components/inspector/PatternInspector.tsx
packages/app/src/components/inspector/ShadowRow.tsx
packages/app/src/containers/Inspector.tsx
packages/app/src/containers/ShadowInspector.tsx
packages/app/src/containers/SwatchesInspector.tsx
packages/app/src/hooks/useLayerMenu.tsx
packages/app/src/utils/getMultiValue.ts
packages/noya-designsystem/src/components/FillInputField.tsx
packages/noya-designsystem/src/theme/dark.ts
packages/noya-designsystem/src/theme/light.ts
packages/noya-state/src/layers.ts
packages/noya-utils/src/__tests__/zip.test.ts
packages/noya-utils/src/zip.ts

The main feature this adds is support for inspecting multiple shadows:
I refactored a bunch of other small things, and plan to refactor the fill picker some more after this.
FYI @milg15

Inspect multiple shadows & refactor color inspector

---

packages/app/src/components/inspector/CoordinatesInspector.tsx
packages/app/src/containers/ControlPointCoordinatesInspector.tsx
packages/app/src/containers/PointControlsInspector.tsx
packages/noya-state/src/selectors/pointSelectors.ts

We were returning `undefined` instead of `null` in a component. I also included some misc cleanup.

Fix issue where control point selection causes a crash

---

packages/app/src/containers/Canvas.tsx
packages/app/src/containers/Toolbar.tsx
packages/noya-renderer/src/components/SketchFileRenderer.tsx
packages/noya-state/src/reducers/applicationReducer.ts
packages/noya-state/src/reducers/canvasReducer.ts
packages/noya-state/src/reducers/interactionReducer.ts
packages/noya-state/src/selectors/layerSelectors.ts

Allows to select a symbol an drop it into the canvas

Add symbol to page

---

packages/app/package.json
packages/app/src/containers/Canvas.tsx
packages/noya-designsystem/package.json
packages/noya-designsystem/src/hooks/__tests__/mergeEventHandlers.test.ts
packages/noya-designsystem/src/hooks/mergeEventHandlers.ts
packages/noya-designsystem/src/index.tsx
packages/noya-state/src/reducers/applicationReducer.ts
packages/noya-state/src/reducers/canvasReducer.ts
yarn.lock

Sets up [react-use-gesture](https://use-gesture.netlify.app/) to handle panning with a trackpad.

add trackpad panning

---

packages/app/src/components/ImageDropTarget.tsx
packages/app/src/components/inspector/FillInputFieldWithPicker.tsx
packages/app/src/components/inspector/PatternInspector.tsx
packages/app/src/containers/Canvas.tsx
packages/noya-state/src/models/bitmap.json
packages/noya-state/src/models/index.ts
packages/noya-state/src/reducers/applicationReducer.ts
packages/noya-state/src/reducers/canvasReducer.ts

Allows to drag & drop an image into the canvas
| Drag | Drop |
| ------------- | ------------- |
| <img src="https://user-images.githubusercontent.com/16924758/125148904-2b221880-e0fb-11eb-8d27-7b351dfb4543.png" width="350" height="250"> | <img src="https://user-images.githubusercontent.com/16924758/125148924-560c6c80-e0fb-11eb-91d4-583409f29d23.png" width="350" height="250">
* Clean up of (#156)

Drop image to canvas 

---

packages/app/src/containers/Canvas.tsx
packages/noya-import-svg/src/index.ts
packages/noya-renderer/src/components/InsertPointOverlay.tsx
packages/noya-renderer/src/components/PseudoPathLine.tsx
packages/noya-renderer/src/components/SketchFileRenderer.tsx
packages/noya-state/src/index.ts
packages/noya-state/src/primitives/path.ts
packages/noya-state/src/reducers/applicationReducer.ts
packages/noya-state/src/reducers/canvasReducer.ts
packages/noya-state/src/reducers/interactionReducer.ts
packages/noya-state/src/selectors/pointSelectors.ts

TODO: 
- Straight/asymmetric/disjointed lines
- Tests
- Fix rendering order so points appear over pseudo lines
cc @leannepepper in case you're curious how it turned out (so far)!

Insert point on path

---

packages/noya-geometry/src/rect.ts
packages/noya-state/src/reducers/__tests__/__snapshots__/layerReducer.test.ts.snap
packages/noya-state/src/reducers/layerReducer.ts
packages/noya-state/src/selectors/layerSelectors.ts

I can delete the comments later 😅

Update on the paste layers

---

packages/noya-state/src/reducers/canvasReducer.ts

Round numbers

---

packages/app-mobile/src/components/FPSCounter.tsx
packages/app-mobile/src/containers/CanvasRenderer.tsx
packages/app-mobile/src/containers/Toolbar.tsx
packages/noya-native-canvaskit/src/SkiaCanvasKit.ts
packages/noya-renderer/src/components/SketchFileRenderer.tsx

- fixed SketchFileRenderer canvas transform and screen transform groups causing some of the components (like grid pixels) to be created on each render
- fixed color parser in react-native canvaskit class
- commented out mobile fps counter as it generated a lot of noise in profiling tools

Improve performance, fix color parser in rn canvaskit

---

packages/app-mobile/src/App/AppContent.tsx
packages/noya-designsystem/src/components/Popover/Popover.native.tsx
packages/noya-react-utils/src/Portal.tsx
packages/noya-react-utils/src/index.ts
packages/noya-renderer/src/components/GradientEditor.tsx
packages/noya-workspace-ui/src/FillInspector/FillInputFieldWithPicker/GradientFillPicker.tsx
packages/noya-workspace-ui/src/FillInspector/FillInspector.tsx
packages/noya-workspace-ui/src/GradientInspector.tsx

Fixes issue with color picker modal backdrop blocked access to gradient handles on canvas

Fix Color picker

---

packages/app/src/components/inspector/ExportPreviewRow.tsx
packages/app/src/components/theme/CanvasPreviewItem.tsx
packages/app/src/components/theme/Symbol.tsx
packages/app/src/components/theme/TextStyle.tsx
packages/app/src/components/theme/ThemeStyle.tsx
packages/app/src/containers/CanvasViewer.tsx
packages/app/src/containers/Menubar.tsx
packages/app/src/containers/PageList.tsx
packages/app/src/containers/PagePreviewItem.tsx
packages/app/src/containers/PagesGrid.tsx
packages/noya-app-state-context/src/useWorkspace.tsx
packages/noya-designsystem/src/components/Label.tsx
packages/noya-embedded/src/applicationMenu.ts
packages/noya-state/src/reducers/workspaceReducer.ts

Add preference for showing page list thumbnails

---

packages/site/src/__tests__/__snapshots__/renderBlock.test.ts.snap
packages/site/src/ayon/blocks/AvatarBlock.tsx
packages/site/src/ayon/blocks/ButtonBlock.tsx
packages/site/src/ayon/blocks/CheckboxBlock.tsx
packages/site/src/ayon/blocks/InputBlock.tsx
packages/site/src/ayon/blocks/RadioBlock.tsx
packages/site/src/ayon/blocks/SelectBlock.tsx
packages/site/src/ayon/blocks/SidebarBlock.tsx
packages/site/src/ayon/blocks/SwitchBlock.tsx
packages/site/src/ayon/blocks/TableBlock.tsx
packages/site/src/ayon/blocks/TextareaBlock.tsx
packages/site/src/ayon/blocks/blockTheme.ts
packages/site/src/ayon/blocks/index.ts
packages/site/src/ayon/blocks/symbols.ts
packages/site/src/ayon/parse.ts

Improves Table, Switch, Checkbox, Button, Input, Avatar

Add Select, Radio, and Textarea blocks, improve various existing blocks

---

packages/noya-canvas/src/components/Canvas.tsx
packages/noya-canvas/src/components/CanvasElement.tsx
packages/noya-canvas/src/hooks/useCopyHandler.tsx
packages/noya-canvas/src/hooks/usePasteHandler.ts
packages/noya-keymap/src/hooks.ts

Fix copy & paste within blocks being handled globally
